# Generated by Django 3.1.7 on 2021-03-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.TextField()),
                ('studentemail', models.TextField()),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
