# Generated by Django 3.1.7 on 2021-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210326_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='interviewername',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidateemail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidatename',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='green', max_length=255),
        ),
    ]
