# Generated by Django 3.1.7 on 2021-04-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210331_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interview',
            name='question',
            field=models.CharField(choices=[('What is DBMS?', 'What is DBMS?'), ('What is the use of paging in operating system?', 'What is the use of paging in operating system?'), ('What is a Stack?', 'What is a Stack?'), ('What are the basic concepts of OOPS?', 'What are the basic concepts of OOPS?'), ('What is a checkpoint in DBMS?', 'What is a checkpoint in DBMS?'), ("What is Banker's algorithm?", "What is Banker's algorithm?"), ('Explain what is Computer Architecture?', 'Explain what is Computer Architecture?'), ('Define overloading and overriding in OOPS?', 'Define overloading and overriding in OOPS?'), ('List the area of applications where stack data structure can be used?', 'List the area of applications where stack data structure can be used?'), ('What is OOPS?', 'What is OOPS?'), ('What is an operating system?', 'What is an operating system?'), ('What are the advantages of DBMS?', 'What are the advantages of DBMS?')], default='', max_length=255),
        ),
    ]
